server:
  name: "SFaction"
  type: DEFAULT
mongo:
  ip: "148.113.191.109"
  port: 27017
  database: "admin"
  auth:
    enabled: true
    username: "adminxminelc"
    password: "Xm1n3lc_Network_2026#"
redis:
  address: "172.18.0.1"
  port: 6379
  auth:
    enabled: true
    password: "XmiN3lc.Secur3.Db!"

queue-manager:
  enabled: true
  queues:
    - "SFaction"
    - "Skyblock"
  hub-server: "Lobby"
  hub-aliases:
    - "hub"
    - "lobby"