server:
  name: "Unconfigured"
  type: DEFAULT
mongo:
  ip: "127.0.0.1"
  port: 27017
  database: "Circuit"
  auth:
    enabled: false
    username: ""
    password: ""
redis:
  address: "127.0.0.1"
  port: 6379
  auth:
    enabled: false
    password: ""

queue-manager:
  enabled: false
  queues:
    - "Squads"
    - "Kitmap"
  hub-server: "Hub-01"
  hub-aliases:
    - "hub"
    - "lobby"